apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: result
  name: result
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/result
spec:
  replicas: 4
  selector:
    matchLabels:
      app: result
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: result
      name: result
    spec:
      containers:
      - image: mekenthompson/example-voting-app-result
        imagePullPolicy: Always
        name: result
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: result
  name: result
  selfLink: /api/v1/namespaces//services/result
spec:
  clusterIP: 
  ports:
  - name: 
    nodePort: 31811
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: result
  sessionAffinity: None
  type: LoadBalancer
status: